name: Test workflow

on:
  workflow_dispatch:
    inputs:
      offerName:
        description: 'Offer name'
        required: true
      planName:
        description: 'Plan name'
        required: true
      filePath:
        description: 'Artifact file path'
        required: true
      artifactVersion:
        description: 'Artifact version'
        required: true
        default: '1.0.0'

env:
    offerName: ${{ github.event.inputs.offerName }}
    planName: ${{ github.event.inputs.planName }}
    filePath: ${{ github.event.inputs.filePath }}
    artifactVersion: ${{ github.event.inputs.artifactVersion }}
    clientId: ${{ secrets.CLIENT_ID }}
    secretValue: ${{ secrets.SECRET_VALUE }}
    tenantId: ${{ secrets.TENANT_ID }}

jobs:
  update_artifact_job:
    runs-on: ubuntu-latest
    name: A job to update Partner Center offer artifact
    steps:
      - name: Checkout microsoft-partner-center-action
        uses: actions/checkout@v2
        with:
          repository: zhengchang907/microsoft-partner-center-action
          path: microsoft-partner-center-action
      - name: Update offer artifact
        id: hello
        uses: zhengchang907/microsoft-partner-center-action@v1
        with:
          offerName: ${{ env.offerName }}
          planName: ${{ env.planName }}
          filePath: ${{ env.filePath }}
          artifactVersion: ${{ env.artifactVersion }}
          clientId: ${{ env.clientId }}
          secretValue: ${{ env.secretValue }}
          tenantId: ${{ env.tenantId }}
           
